db.user=Banking_owner
db.password=npg_NPTmM9bdCoZ5
db.url=jdbc:postgresql://ep-fancy-term-a1ddi401-pooler.ap-southeast-1.aws.neon.tech/fraud_detection_db?sslmode=require
db.driver=org.postgresql.Driver
